spring.application.name=lab

# URL de conexión a la base de datos 'carrito_app'
spring.datasource.url=jdbc:mysql://localhost:3306/carrito_app?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=aplicaciones
spring.datasource.password=App:Cifrado

# Connector
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 'update' crea las tablas automáticamente si no existen o las actualiza si cambias las entidades
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
